config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"
  get "tasks/:id", to: "tasks#show", as: "task"
  get "tasks/:id/edit", to: "tasks#edit", as: "task_edit"
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only:[:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path(@task)
  end

  def show

  end

  def edit

  end

  def update
    @task.update(task_params)
    redirect_to tasks_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager2</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_area :title, class: "form-control form-input" %>
  </div>
  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_area :details, class: "form-control form-input" %>
  </div>
   <div class="form-group">
    <%= f.label :completed %>
    <%= f.check_box :completed, class: "form-control form-input"%>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="form-container">
    <div class="offset-md-4 col-md-4 form">
    <div class="title">
    <h1>Edit this task</h1>
      <%= link_to tasks_path do %>
        <i class="fa fa-home"></i>
      <% end %>
    </div>
      <%= render "form", task: @task %>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <div class="index-container">
    <div class="offset-md-4 col-md-4 form">
      <div class="title">
        <h1 class="underline">Task List</h1>
          <%= link_to tasks_new_path do %>
            <i class="fa fa-plus"></i>
          <% end %>
      </div>
      <div class="tasks">
      <% @tasks.each do |task| %>
        <% unless task.completed %>
        <div class="this">
          <div class="check-box">
            <%= link_to task_edit_path(task) do %>
              <i class="fa fa-pencil"></i>
            <% end %>
            <%= link_to task_path(task),
              method: :delete,
              data: {confirm: "Are you sure?" } do %>
              <i class="fa fa-trash"></i>
          <% end %>
          </div>
          <div class="task-list">
          <p><%= link_to task.title, task_path(task) %></p>
          </div>
        <% end %>
         </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <div class="form-container">
    <div class="offset-md-4 col-md-4 form">
    <div class="title">
    <h1>Add a new task</h1>
      <%= link_to tasks_path do %>
        <i class="fa fa-undo"></i>
      <% end %>
    </div>
      <%= render "form", task: @task %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="form-container">
    <div class="offset-md-4 col-md-4 form">
      <div class="title">
      <h1><%= @task.title %></h1>
        <%= link_to task_edit_path(@task) do %>
          <i class="fa fa-pencil"></i>
        <% end %>
      </div>
      <div class="tasks-container">
      <div class="task-details">
        <p><%= @task.details %></p>
      </div>
          </div>
        <%= link_to tasks_path do %>
          <i class="fa fa-undo"></i>
        <% end %>
    </div>


  </div>
</div>

app/views/tasks/update.html.erb
<h1>Edit</h1>
<%= link_to "Tasks", tasks_path %>